version: '2'
services:
    vacunas-app:
        image: vacunas
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://vacunas-mysql:3306/vacunas?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    vacunas-mysql:
        extends:
            file: mysql.yml
            service: vacunas-mysql
